<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>spineviewer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
  </ItemGroup>
</Project>